[project]
name = "nanogpt"
version = "0.1.0"
description = "Experiments with NanoGPT from Karpathy"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beartype>=0.21.0",
    "datasets>=4.0.0",
    "einops>=0.8.1",
    "hydra-core>=1.3.2",
    "jaxtyping>=0.3.2",
    # Platform-specific lightning versions
    #"lightning>=2.5.2; sys_platform != 'linux' or python_version < '3.12'",
    #"lightning==2.6.0.dev20250713; sys_platform == 'linux' and python_version >= '3.12'",
    "lightning>=2.5.2",
    "matplotlib>=3.10.3",
    # Platform-specific pandas versions
    #"pandas>=2.3.1; sys_platform != 'linux' or python_version < '3.12'",
    #"pandas==2.2.3; sys_platform == 'linux' and python_version >= '3.12'",
    "omegaconf>=2.3.0",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "psutil",
    "pyyaml>=6.0.2",
    "seaborn>=0.13.2",
    "setuptools>=80.9.0",
    "tiktoken>=0.9.0",
    # Platform-specific tokenizers versions
    #"tokenizers>=0.21.2; sys_platform != 'linux' or python_version < '3.12'",
    #"tokenizers==0.21.4.dev0; sys_platform == 'linux' and python_version >= '3.12'",
    # Platform-specific torch versions
    #"torch>=2.7.1; sys_platform != 'linux' or python_version < '3.12'",
    #"torch==2.8.0a0+5228986c39.nv25.5; sys_platform == 'linux' and python_version >= '3.12'",
    "tokenizers>=0.21.4",
    "torch>=2.7.1",
    "tqdm>=4.67.1",
    # Platform-specific transformers versions
    #"transformers>=4.51.3; sys_platform != 'linux' or python_version < '3.12'",
    #"transformers>=4.51.3,<4.54.0; sys_platform == 'linux' and python_version >= '3.12'",
    "wandb>=0.21.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.json", "*.yaml", "*.yml"]

[project.scripts]
train-gpt2 = "scripts.train_gpt2:main"
train-super-gpt2 = "scripts.train_super_gpt2:main"
evaluate-models = "scripts.evaluate_models:main"

